import type { Metadata } from "next";
import { Montserrat, Chelsea_Market } from "next/font/google";
import "./globals.css";

// Montserrat (todos os pesos e estilos)
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ],
  style: ["normal", "italic"],
  display: "swap",
});

// Chelsea Market (único peso)
const chelseaMarket = Chelsea_Market({
  variable: "--font-chelsea",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ONG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${chelseaMarket.variable} antialiased text-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}
